name: with_controller
description: A package provinding the WithController widget. It is a convenience widget for reducing MobX boilerplate burden when you need to initialize a store, create reactions and dispose.
version: 1.0.1+1

homepage: https://github.com/savioserra/with_controller

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  mobx: ^2.0.0-nullsafety.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
